# Site settings
title: Rodrigo Lopes
description: Resume
baseurl: "/rfalopes" # the subpath of your site, e.g. /blog
url: "https://rfa-lopes.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rodrigo Lopes
user_description: Resume
user_title: Computer Science Student at FCT@UNL, in final year of master's degree #Software Engineer
email: rfa.lopess@gmail.com
# twitter_username: lorem_ipsum
github_username: rfa-lopes
# gplus_username:  lorem_ipsum

exclude: ["package.json", "src", "node_modules"]


google_ad_client: 5353808927577681
google_tracking_id: G-8CDPS3ZJPS
